ignored:
  - DL3018  # Ignorer le warning sur les versions pinnees Alpine
  - DL3008  # Ignorer le warning sur les versions pinnees apt

trustedRegistries:
  - docker.io
  - ghcr.io

failure-threshold: warning
